version: '3.7'
services:
  sleekpigeons:
    build:
      context: .
      target: dev
    ports:
      - "80:80"
    volumes:
      - ./nginx:/nginx
      - ./www:/www
      - ./logs:/var/log/nginx
    environment:
      - FINNHUB_KEY
