version: '3.7'
services:
  sleekpigeons:
    build:
      context: .
      target: base
    ports:
      - "80:80"
      - "3903:3903"
      - "9090:9090"
    volumes:
      - ./nginx:/nginx
      - ./www:/www
      - ./mtail:/etc/mtail
    environment:
      - FINNHUB_KEY
      - QUANDL_KEY
