version: '3.7'
services:
  sleekpigeons:
    build:
      context: .
      target: dev
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/www
    environment:
      - FINNHUB_KEY
