name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:	
    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v2	

    - name: Login to Docker Hub	
      run: docker login -u phillaf -p ${{ secrets.DOCKERHUB_PASS }}	

    - name: Build Docker image	
      run: docker build -f ./docker/build/Dockerfile -t phillaf/sleekpigeons:latest .

    - name: Publish Docker image	
      run: docker push phillaf/sleekpigeons
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}

